[package]
name = "solfig"
version = "0.1.1"
edition = "2021"
description = "SOLFIG — a TUI for the Solana CLI config"
authors = ["rokoperki"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rokoperki/solfig"
homepage = "https://github.com/rokoperki/solfig"
readme = "README.md"
keywords = ["solana", "tui", "cli", "config", "wallet"]
categories = ["command-line-utilities"]

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
serde = { version = "1", features = ["derive"] }
serde_yaml = { package = "serde_yaml_ng", version = "0.10" }
dirs = "6"
anyhow = "1"
bs58 = "0.5"
ureq = { version = "2", features = ["json"] }
serde_json = "1"
arboard = "3"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
